url: https://mmcartons.github.io
baseurl: /mmcartons.github.io/

# Site settings
title: M.M Cartons-Corrugated Boxes Chennai
email: info@mmcartons.in
description: "Corrugated Box Manufacturer. we help customers with variety of custom corrugated packaging solution. We specialize in making corrugated boxes for export & other Industrial packaging."


# Team names, titles and social links
people:
- name: Mohamed Ikbal
  pic: 1
  position: Managing Director

- name: Fathima Ikbal
  pic: 2
  position: Proprietor


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: No 21, Muthiyal Street, Alandur
  - line: St Thomas Mount, Chennai - 600016, Near Market

# Build settings
markdown: kramdown
permalink: pretty
